language: cpp
cache:
  directories:
  - build_linux/absl
  - build_linux/cctz
  - build_linux/googletest
  - build_linux/openssl
  - build_linux/postgresql
  - build_linux/protobuf
os:
- linux
dist: trusty
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_e7d783d52fe7_key -iv $encrypted_e7d783d52fe7_iv
  -in third_party/idasdk70.zip.enc -out third_party/idasdk70.zip -d
- unzip -q third_party/idasdk70.zip -d third_party/
script:
- mkdir -p build_linux
- cd build_linux
- cmake ../cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_RULE_MESSAGES=OFF -DIdaSdk_ROOT_DIR=$PWD/../third_party/idasdk70
- cmake --build .
