language: cpp

cache:
  directories:
    - $HOME/protobuf
    - $HOME/postgresql

os:
  - linux

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-4.8
      - lib32stdc++-4.8-dev
      - libssl-dev:i386

sudo: false

before_install:
  - export CXX=g++-4.8 CC=gcc-4.8

  # IDA SDK
  - openssl aes-256-cbc -k "$idasdk_secret" -in third_party/idasdk.zip.enc
    -out third_party/idasdk.zip -d
  - unzip -q third_party/idasdk.zip -d third_party/

  # Cached PostgreSQL client libraries
  - test ! -f "$HOME/postgresql/CACHED" && true || export C_POSTGRES=1
  - test -n "$C_POSTGRES" && true ||
    wget https://ftp.postgresql.org/pub/source/v9.5.3/postgresql-9.5.3.tar.bz2
  - test -n "$C_POSTGRES" && true || tar xaf postgresql-9.5.3.tar.bz2
  - test -n "$C_POSTGRES" && true || cd postgresql-9.5.3
  - test -n "$C_POSTGRES" && true ||
    ./configure CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32
    --prefix=$HOME/postgresql --disable-debug --disable-profiling
    --disable-coverage --without-tcl --without-perl --without-python
    --without-gssapi --without-ldap --without-bonjour --without-readline
  - test -n "$C_POSTGRES" && true || make -is -C src/include install
  - test -n "$C_POSTGRES" && true || make -s -C src/interfaces install
  - test -n "$C_POSTGRES" && true || touch "$HOME/postgresql/CACHED"
  - test -n "$C_POSTGRES" && true || cd ..

  # Cached Protocol Buffers
  - test ! -f "$HOME/protobuf/CACHED" && true || export C_PROTOBUF=1
  - test -n "$C_PROTOBUF" && true || cd third_party/protobuf
  - test -n "$C_PROTOBUF" && true || ./autogen.sh
  - test -n "$C_PROTOBUF" && true ||
    ./configure CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 --prefix=${HOME}/protobuf
    --disable-dependency-tracking --disable-maintainer-mode
    --enable-silent-rules
  - test -n "$C_PROTOBUF" && true || make -s
  - test -n "$C_PROTOBUF" && true || make install
  - test -n "$C_PROTOBUF" && true || touch "$HOME/protobuf/CACHED"
  - test -n "$C_PROTOBUF" && true || cd ../..

script:
  - ./configure
    -DOPENSSL_ROOT_DIR=$PWD/third_party/openssl
    -DOPENSSL_CRYPTO_LIBRARY=/usr/lib/i386-linux-gnu/libcrypto.a
    -DOPENSSL_SSL_LIBRARY=/usr/lib/i386-linux-gnu/libssl.a
    -DPostgreSQL_ROOT=$HOME/postgresql
    -DPROTOBUF_ROOT_FOLDER=$HOME/protobuf
    -DPROTOBUF_INCLUDE_DIR=$HOME/protobuf/include
    -DPROTOBUF_PROTOC_EXECUTABLE=$HOME/protobuf/bin/protoc
    -DPROTOBUF_LIBRARY=$HOME/protobuf/lib/libprotobuf.a
  - make

env:
  global:
    - secure: I0+67gZa3t6ADrBEYlTx3+auun2jxPRzk1wZtUDT+5ePGN+EnPKpr496SMShUdg/0dJzw93ZuYXN9jIW2bC9o+aG6fZNQ1kJVxzul6bKqDte6K6Sz8C3Db3HYi+LDkHI2frgwFMDSHzsnag4+BThcgY+jnJeZA9ABxG1NbWpQlTROwl4HhU7TQBt18+kJsnq3QrDqVECTS/MrghECRhs9aR0MQ85wTG2RtS/pGHIjEt5JIrz6bBnTetbdHaMKJR9awSuNqhQmaNkE4tX1IxEFt8YnzIk169diagl9v3CD/DHeM1AaB9iQwjf5PcOGruDhLlxwr1em0NNzrqALRrpBA+I4qKt13yASRSiwBAZicEEjtOFA8ga37wB0r8MGc0Jafw8o+FxpEh9hidkI3gIbF8qPpxkev14SwoAIhZWyAasoHJfw0LjEGk6ProavuVzFsB7BVNqj5sDIr2WFrska7he/x807edSGJEVjwaE6n/n5KF10K2E4ufehS6yR5tcP7Aj5NrKJK5qx6L4XpwdPeAnwnWpnw0qU4bRW4M33ZfpStkmDf5TZwtm742g4A7NhJBezWssQqhMCKB/fQVXtm+svnoHIof5pygR4D8aEnGhTl24JU/8G2Ar7n9PwTIwjjeWlnEKw++8ipTGmVmJnf4zLkoofBBIrSU6tNViJTE=
