language: cpp

cache:
  directories:
    - build_linux/openssl
    - build_linux/protobuf
    - build_linux/postgresql

os:
  - linux

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-4.8
      - lib32stdc++-4.8-dev
      - libssl-dev:i386

sudo: false

before_install:
  - export CXX=g++-4.8 CC=gcc-4.8

  # IDA SDK
  - openssl aes-256-cbc -k "$idasdk_secret" -in third_party/idasdk.zip.enc
    -out third_party/idasdk.zip -d
  - unzip -q third_party/idasdk.zip -d third_party/

script:
  - cd build_linux
  - cmake .. -DCMAKE_RULE_MESSAGES=OFF -DCMAKE_BUILD_TYPE=Release
  - make

env:
  global:
    - secure: U69GqsmS5MdXdACYjNZN3TVxU6nBYDjvBSRR2Ae/nPHdAfaGEZFbhJlQwcsFdOAA8b5h5AUUaFh2PCTXHTt/6HkNcpu8tvFLTJFih3jE4jomEwb9K2N9Q0qpJzOSiy05LylhHq4O9NF7mErm+M5Mijq9kI0oWc4a72/eV8a9TyC80WoDMqLzrTW2X1CAMIqGogcEvyCmyXPaohknolyv7H07W395ddr3mr+j50gHWGNwoPncj2LfU5qEALRmtLuOxFGghnB8Zs+pekAMMg/k7r52cyUyE9wiaujYmq0bdkz3a2Hb8EYuHbtPomQFb7Fd18ACWW2Pvrv7iN8BEQIGsBJZk3tGUyIj9Nh2F8W5r0nxLmTyGcnU8LO5nWaQhatGgLTCi7amhERVAqCiytT1DC6gw0hEN5H2sDFZfnEpn+RURMqiL6Is8xpmK2o5Hc4/mmLm+VGr6ixIxie7qqnpkrTvlVWtuh61qk8K6U6CQaIe11oNZnkRrGa87/u3nHhDX9XFt0T8QFmiWObmV+sa9AIoazGK+2OHp6M42TX9p6eKg8pSJyMEJiCRTw4uS65H+0GDR/tIzMDVdOOWN35mhLPwILJX5ns8krei4y6lbiGoOKGWm5vSXkt/lI16/laUa3DAImFXgth2QlcunJT6yBs0aE/mQWX30XMDNXVKH0I=
